name: Trigger pipeline on Release

on:
  release:
    # type of release to trigger the pipeline check https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
        azure-devops-project-url: https://dev.azure.com/OutSystemsRD/MABS
        # Name of the Azure Pipeline to be triggered
        azure-pipeline-name: OutSystems.cordova-outsystems-barcode
        # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
        azure-devops-token: ${{secrets.AZURE_DEVOPS_TOKEN}}